blank_issues_enabled: true
contact_links:
  - name: 📝 Official Documentation 
    url: https://guides.getalby.com/
    about: Check our documentation for answers to common questions.
  - name: 💬 Community Chat
    url: https://web.telegram.org/z/#-1518893230
    about: Ask general questions, discuss ideas and get support.